tupla = ("manzana","banano","chontaduro","mango","mango")
tupla2 = (1,2,3,4,5)
tupla3 = (True, False, False)
tupla4 = ("kiwi", 3, True)
tuplaCons = tuple(("cadena",6,False))
print(tupla)
print(type(tupla))
print(len(tupla))
print(tupla2)
print(tupla3)
print(tupla4)
print(tuplaCons)